controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

connect_google_check:
    path: /oauth/check/google
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController

connect_facebook_check:
    path: /oauth/check/{service}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
